version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - '3306:${DB_PORT}'
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}", "-e", "SELECT 1"]
      timeout: 1s
      retries: 10
    networks:
      - network-1

  redis:
    image: 'redis:alpine'
    restart: always
    hostname: redis
    ports:
      - '6379:${REDIS_PORT}'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 1s
      retries: 5
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - network-1

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network-1
    healthcheck:
      test: [ 'CMD-SHELL', 'rabbitmqctl status' ]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9006:9000"
      - "9007:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

volumes:
  mysql_data:
  redis_data:
  kong_data:

networks:
  network-1:
    driver: bridge
