# Generated by Django 5.1.2 on 2024-11-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(related_name='teachers', through='departments.TeacherDepartment', to='departments.department'),
        ),
    ]
