# Generated by Django 5.1.2 on 2024-10-22 07:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='major_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
