# Generated by Django 5.0.2 on 2024-07-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
