# Generated by Django 5.1.2 on 2024-10-22 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_thesis_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaterial',
            name='subject_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
