# Generated by Django 5.1.1 on 2024-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='scope',
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(null=True, related_name='users', to='users.role'),
        ),
    ]
